// PlanarQuant: K=PQ4_0, V=PQ4_0 (max compression)

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_PQ4_0, GGML_TYPE_PQ4_0);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_PQ4_0, GGML_TYPE_PQ4_0);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_PQ4_0, GGML_TYPE_PQ4_0);
